apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fiware-dsc-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: fiware-dsc
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: authentication-mysql
      namespace: fiware-dsc
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
    - group: apps
      kind: StatefulSet
      name: data-service-postgis
      namespace: fiware-dsc
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
    - group: apps
      kind: StatefulSet
      name: fiware-dsc-etcd
      namespace: fiware-dsc
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
    - group: apps
      kind: StatefulSet
      name: postgresql
      namespace: fiware-dsc
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
  sources:
    - repoURL: https://fiware.github.io/data-space-connector/
      chart: data-space-connector
      targetRevision: 8.5.2
      helm:
        releaseName: fiware-dsc
        skipCrds: true
        valueFiles:
          - $values/plaform-apps/fiware-dsc/values.yaml
    - repoURL: https://github.com/Data-Space-Core/FIWARE-Connector.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: fiware-dsc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
