apiVersion: v1
kind: Namespace
metadata:
  name: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-database-secret
  namespace: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  mysql-root-password: password
  mysql-password: password
  mysql-replication-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  postgres-admin-password: fiwareuser
  postgres-user-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
  namespace: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  postgres-admin-password: fiwareuser
  postgres-user-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: issuance-secret
  namespace: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  keycloak-admin: admin
  keycloak-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: kc-keystore
  namespace: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: fiware-dsc-etcd-jwt-token
  namespace: fiware-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  jwt-token.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDG+Zdv/Bveyj63
    oTYN7ExxYsQ2Ld3qCKI20bLTEQuz76/6M44ozzW8kyxVLdqJFvy2c8AQs33Uec1B
    jFxeNg9qnj+1jdRGqeN4pwkCBd4ZSNof8nR0gYJbEsEZBIOBKi6rvwpZyGD+Jn2z
    D+dAvQoxbIDvEguuwEadPGoK7OfVcz3kJvvlk14R8tcNSlmxIx5Dnrom+yUSeX3K
    7D4TLJtakFmCqCFm3SetDR9xLmmsQqVKTD27kWaY4rI/1ii1d66ju54kD9NC/TXy
    SCY895GIZlMqVPPSOHYRDNFALL2IBogBnspWATLrYEGeMpanLxxhZgy83/KYEj32
    cBmx8KlRAgMBAAECggEAAeOLEhTPIQ4HxqcEDr9g1zGk1EIJm6kCY1aRNNBDRxxn
    pWPcszcCNwyYNlfbfaEh962yJu3m31ufC7od6Y6B0ih7wL5C3Vjc2c5+QcxCVAVA
    fedHlEON7+djzmlCKHVW2nsPHuU0ES0JstaGvmZRReujGW6xFsQgPNCLmsKuCUIC
    QDRXYcTrW66zDmqPJl7jcQnRpz4TtaZUuNf+PlaSrBysYuhbRtTw7HipGanGhxab
    JxXpA52SFHFcOahdq3MezH7kHUA+7vLpTTL1dEHgTi6cm1i0LzTHEO793UvCuAzH
    xUJAFaFf8vFX/HPzFak4DtSo1W7dHUVlZnQNIHd7cQKBgQDnAhq6H42ECsyaj95A
    kFUFffojP+zcAqKPjrsia3w8kL8Gms3Xk91sbbXv9lov0WQ0SjmtRt6rE4KGxBV1
    2l0c6oX02BV39scxCABWwgD4xgGT+wnQNC+XRKEYfNecdxmpujZXUj2AWJwcM8xb
    ug+tLKUid78iOcynxIg71a7cOwKBgQDcgE8kmEBQEbbwwY7lgGtAolcABqjHCNrk
    esXWqcRdPp7AssRSRzkcb4S8L1vGEEegzgmGgEDnPiv+IU+77fs/sZnsSImypRnv
    XNdXwh/X1IFyHdsUEpxmYQa3U/JBn8e+YuMDd+qpAYAdizwsqDJ6fOFQVe5/OOsO
    vYsZHvET4wKBgQDjxNVpcrbr3GIEe5nd+vF5qs65dswp2YdDGK42r9gdN3LCJlyT
    FD4cLMhYw4QE5eZxEEZyLRBbia8HBctLGnT4j9xon637TJz2ITeEU2D16PWhXMI+
    QVYzRf240U8d/OiWyv3Nd08gfz3dKM10G65dR0nDBGK2clrxh/vzUytIBQKBgQDP
    h+v1M18EfUfDXUmS88T+NkzP93SOr+TlOjBOE8Z/RFrCXv6rueEkxEkXnTMxPU1N
    Kd6JOtjbTAa3zr5u0FOy5QNMAhGnlADO6oC7VjgGOToEH9l8EPAm45cgoN/Xp/yl
    Ugj70LeJjaH5LHzcQwoPgs3FgLtR/k4tt3PdluOrpQKBgGyia+4tXQolvpaxpgfd
    Xbp6rbt7k+q4Xs+Wt18XhXXkYqIVy0Bzh4blrZmwPpqAbVOir1lRxV0b/xeOfzX8
    8GGxDLIEKj+1M/ZbBcOFJ7dLBvHgrsuln6FmusnZugD1ZznVZKxAQakbQk2FEUlN
    XCrtOgg9WraUSQjZqyW1929D
    -----END PRIVATE KEY-----
