apiVersion: v1
kind: Namespace
metadata:
  name: fiware-dsc

---
apiVersion: v1
kind: Secret
metadata:
  name: authentication-database-secret
  namespace: fiware-dsc
type: Opaque
stringData:
  mysql-root-password: password
  mysql-password: password
  mysql-replication-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: fiware-dsc
type: Opaque
stringData:
  postgres-admin-password: fiwareuser
  postgres-user-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-secret
  namespace: fiware-dsc
type: Opaque
stringData:
  postgres-admin-password: fiwareuser
  postgres-user-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: issuance-secret
  namespace: fiware-dsc
type: Opaque
stringData:
  keycloak-admin: admin
  keycloak-password: password

---
apiVersion: v1
kind: Secret
metadata:
  name: kc-keystore
  namespace: fiware-dsc
type: Opaque
stringData:
  password: password